// Block A5 — agent-level shadow mode (architect first).
//
// Per the approved plan at `~/.claude/plans/rate-this-plan-zesty-tiger.md`,
// V2 agent runners run in shadow mode alongside legacy production handlers
// for 48h before any cutover. Shadow:
//   - reads the same state the production handler reads
//   - classifies which V2 branch would be taken
//   - logs `[V2-ARCHITECT-SHADOW] feature=<x> branch=<y> ...` for operator review
//   - DOES NOT mutate conversation-store state
//   - DOES NOT post to Slack
//   - DOES NOT call the LLM
//
// This is the minimal-cost initial shadow: classifier-only. Subsequent
// commits expand it to log proposed deterministic text (state-query,
// off-topic, approval-confirm renderers) and proposed LLM-call shape
// (escalation-engaged, normal-agent-turn).
//
// The function is fire-and-forget: it must never throw, never block the
// handler, and never alter production state. Same shape as
// `runtime/routing/shadow.ts` (Phase 3 routing shadow, the precedent).
//
// DESIGN-REVIEWED: agent-level shadow per Principle 12. (1) Scales because
// shadow is per-message-per-agent and adds only classifier work (O(1));
// the LLM and deterministic-rendering branches don't actually run. (2)
// Owned by this module exclusively; production handlers call into it as
// a side-effect-free observer. (3) Cross-cutting: every V2 runner gets a
// shadow wrapper of this same shape; designer + PM shadows in A6/A7
// follow this pattern, generated by Block M1's scaffold script.

import { buildReadinessReport, type ReadinessReportInput } from "../readiness-builder"
import {
  classifyArchitectBranch,
  type ArchitectIntent,
  type ArchitectStateFlags,
} from "./runArchitectAgentV2"
import {
  classifyDesignBranch,
  type DesignIntent,
  type DesignStateFlags,
} from "./runDesignAgentV2"

export type ArchitectShadowParams = {
  readonly featureName:  string
  readonly userMessage:  string
  readonly intent:       ArchitectIntent
  readonly state:        ArchitectStateFlags
  readonly reportInput:  ReadinessReportInput  // production handler hands off the input it already has
}

// Logs one line per shadow invocation:
//   [V2-ARCHITECT-SHADOW] feature=<x> branch=<y> aggregate=<z> total=<n>
// Operators correlate this with legacy's actual response (also logged) to
// detect divergences during the 48h burn-in window.
//
// Returns silently (void). Logs an error line on any internal failure but
// doesn't throw — the production handler MUST keep working regardless.
export function shadowArchitectV2(params: ArchitectShadowParams): void {
  try {
    const report = buildReadinessReport(params.reportInput)
    const branch = classifyArchitectBranch({
      report,
      intent: params.intent,
      state:  params.state,
    })
    console.log(
      `[V2-ARCHITECT-SHADOW] feature=${params.featureName} branch=${branch} aggregate=${report.aggregate} total=${report.totalFindingCount}`,
    )
  } catch (err) {
    console.log(
      `[V2-ARCHITECT-SHADOW-ERROR] feature=${params.featureName} reason=${String(err).slice(0, 200)}`,
    )
  }
}

export type DesignShadowParams = {
  readonly featureName:  string
  readonly userMessage:  string
  readonly intent:       DesignIntent
  readonly state:        DesignStateFlags
  readonly reportInput:  ReadinessReportInput
}

// Block A6 designer shadow. Same shape as the architect shadow above.
// Logs `[V2-DESIGNER-SHADOW] feature=<x> branch=<y> aggregate=<z> total=<n>`
// per designer-bound message during the 48h burn-in. Never throws, never
// posts, never mutates state, never calls the LLM.
export function shadowDesignerV2(params: DesignShadowParams): void {
  try {
    const report = buildReadinessReport(params.reportInput)
    const branch = classifyDesignBranch({
      report,
      intent: params.intent,
      state:  params.state,
    })
    console.log(
      `[V2-DESIGNER-SHADOW] feature=${params.featureName} branch=${branch} aggregate=${report.aggregate} total=${report.totalFindingCount}`,
    )
  } catch (err) {
    console.log(
      `[V2-DESIGNER-SHADOW-ERROR] feature=${params.featureName} reason=${String(err).slice(0, 200)}`,
    )
  }
}
