// Block M1 of the approved system-wide plan
// (~/.claude/plans/rate-this-plan-zesty-tiger.md). New-agent scaffold
// script. Generates the skeleton files a new agent needs and prints the
// remaining manual steps from docs/CONTRIBUTING_AGENTS.md so the author
// has a checklist to drive against.
//
// Usage:
//   npx tsx scripts/scaffold-agent.ts <agent-name> [--dry-run]
//
// Example:
//   npx tsx scripts/scaffold-agent.ts coder
//
// Generates:
//   agents/<name>.ts                                 — skeleton prompt builder + tools
//   tests/unit/<name>-prompt.test.ts                 — smoke test for the prompt builder
//   tests/fixtures/agent-output/<name>/.gitkeep      — placeholder for real-fixture tests
//
// Then prints the remaining manual steps from CONTRIBUTING_AGENTS.md.

import * as fs from "node:fs"
import * as path from "node:path"

interface CliArgs {
  name:    string
  dryRun:  boolean
}

function parseArgs(argv: string[]): CliArgs {
  const args: Partial<CliArgs> = { dryRun: false }
  for (const a of argv) {
    if (a === "--dry-run") { args.dryRun = true; continue }
    if (a.startsWith("--")) continue
    if (!args.name) args.name = a
  }
  if (!args.name) {
    throw new Error("Usage: npx tsx scripts/scaffold-agent.ts <agent-name> [--dry-run]")
  }
  if (!/^[a-z][a-z0-9-]*$/.test(args.name)) {
    throw new Error(`Invalid agent name: "${args.name}". Use lowercase kebab-case (e.g. "coder", "frontend").`)
  }
  return args as CliArgs
}

function pascalCase(name: string): string {
  return name.split("-").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("")
}

function upperSnake(name: string): string {
  return name.toUpperCase().replace(/-/g, "_")
}

const REPO_ROOT = path.join(__dirname, "..")

function pathFor(name: string): {
  agentFile:    string
  testFile:     string
  fixtureDir:   string
  fixtureGitkeep: string
} {
  return {
    agentFile:      path.join(REPO_ROOT, `agents/${name}.ts`),
    testFile:       path.join(REPO_ROOT, `tests/unit/${name}-prompt.test.ts`),
    fixtureDir:     path.join(REPO_ROOT, `tests/fixtures/agent-output/${name}`),
    fixtureGitkeep: path.join(REPO_ROOT, `tests/fixtures/agent-output/${name}/.gitkeep`),
  }
}

function buildAgentTemplate(name: string): string {
  const Pascal = pascalCase(name)
  const Upper  = upperSnake(name)
  return `import Anthropic from "@anthropic-ai/sdk"
import { AgentContext } from "../runtime/context-loader"
import { loadWorkspaceConfig } from "../runtime/workspace-config"
import { splitSystemPrompt } from "../runtime/claude-client"
// DESIGN-REVIEWED: Block M1 scaffold. (1) Scale: O(1) — buildAntiDeferralBlock returns a constant string per Block N. (2) Ownership: deterministic-auditor.ts owns DEFERRAL_PHRASES + buildAntiDeferralBlock — same module that owns the runtime hedge gate, single source of truth. (3) Cross-cutting: same block injected into every agent (PM, Designer, Architect, ${name}); cross-agent invariant test enforces parity (Principle 15).
import { buildAntiDeferralBlock } from "../runtime/deterministic-auditor"

// ${Pascal} agent — generated by scripts/scaffold-agent.ts.
// Replace this stub with the agent's domain-specific prompt + tools.
// Then run through the new-agent enforcement checklist in
// docs/CONTRIBUTING_AGENTS.md before the first live test.

export const ${Upper}_TOOLS: Anthropic.Tool[] = [
  // TODO: define this agent's tool set (e.g. save_<name>_spec_draft, apply_<name>_spec_patch).
]

export function build${Pascal}SystemPrompt(context: AgentContext, featureName: string, readOnly = false): string {
  const { productName } = loadWorkspaceConfig()
  return \`You are the ${name} agent for \${productName}.

## Who you are
TODO — write the persona. Reference docs/CONTRIBUTING_AGENTS.md for required sections.

## Domain boundary — what you never own
TODO — enumerate each neighboring agent's exclusive territory.

## Read the room first
When someone introduces themselves or asks an orientation question, orient them (feature, phase, your role) before substantive work.

## Feature context
Feature: \${featureName}
Read-only mode: \${readOnly}

\${buildAntiDeferralBlock()}\`
}

// Two-block system prompt for prompt caching — same pattern as PM/Design/Architect.
export function build${Pascal}SystemBlocks(
  context: AgentContext,
  featureName: string,
  readOnly = false,
): Anthropic.TextBlockParam[] {
  return splitSystemPrompt(
    build${Pascal}SystemPrompt(context, featureName, readOnly),
    "\\n## Feature context",  // split point (uncached portion below this)
  )
}
`
}

function buildTestTemplate(name: string): string {
  const Pascal = pascalCase(name)
  return `import { describe, it, expect } from "vitest"
import { build${Pascal}SystemPrompt } from "../../agents/${name}"
import {
  ANTI_DEFERRAL_BLOCK_MARKER,
  DEFERRAL_PHRASES,
} from "../../runtime/deterministic-auditor"
import type { AgentContext } from "../../runtime/context-loader"

const STUB_CONTEXT: AgentContext = {
  productVision:        "stub",
  featureConventions:   "stub",
  systemArchitecture:   "stub",
  currentDraft:         "",
  approvedFeatureSpecs: "",
  designSystem:         "stub",
  brand:                "stub",
}

describe("${name} agent prompt — scaffold smoke", () => {
  it("builds a non-empty prompt", () => {
    const prompt = build${Pascal}SystemPrompt(STUB_CONTEXT, "test-feature")
    expect(prompt.length).toBeGreaterThan(0)
  })

  it("injects the anti-deferral block (Block N)", () => {
    const prompt = build${Pascal}SystemPrompt(STUB_CONTEXT, "test-feature")
    expect(prompt).toContain(ANTI_DEFERRAL_BLOCK_MARKER)
    for (const phrase of DEFERRAL_PHRASES) {
      expect(prompt).toContain(\`"\${phrase}"\`)
    }
  })

  it("references the feature name", () => {
    const prompt = build${Pascal}SystemPrompt(STUB_CONTEXT, "test-feature")
    expect(prompt).toContain("test-feature")
  })

  // TODO: add domain-specific tests as the agent matures.
  // - Domain boundary section present
  // - Read-the-room orientation instruction present
  // - Tool list non-empty
  // - Cross-agent prompt-contract invariant extended (tests/invariants/anti-deferral-prompt-contract.test.ts)
})
`
}

function writeIfMissing(filePath: string, content: string, dryRun: boolean): "wrote" | "exists" | "would-write" {
  if (fs.existsSync(filePath)) return "exists"
  if (dryRun) return "would-write"
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content)
  return "wrote"
}

function main() {
  const args = parseArgs(process.argv.slice(2))
  const paths = pathFor(args.name)
  console.log(`[scaffold] agent=${args.name} dryRun=${args.dryRun}`)

  const r1 = writeIfMissing(paths.agentFile,      buildAgentTemplate(args.name), args.dryRun)
  const r2 = writeIfMissing(paths.testFile,       buildTestTemplate(args.name),  args.dryRun)
  const r3 = writeIfMissing(paths.fixtureGitkeep, "",                            args.dryRun)
  console.log(`  ${paths.agentFile}: ${r1}`)
  console.log(`  ${paths.testFile}: ${r2}`)
  console.log(`  ${paths.fixtureGitkeep}: ${r3}`)

  console.log(`
[scaffold] Skeleton written. Remaining manual steps (from docs/CONTRIBUTING_AGENTS.md):

  CODE
   - Replace TODOs in agents/${args.name}.ts (persona, domain boundary, tools, prompt body)
   - Add ${args.name} to the prompt-contract invariant: tests/invariants/anti-deferral-prompt-contract.test.ts
   - Add a deterministic auditor for the agent's domain (Principle 11)

  RUNTIME WIRING (interfaces/slack/handlers/message.ts)
   - Add async function run${pascalCase(args.name)}Agent(...)
   - Wire the always-on platform audit block (${args.name}ReadinessNotice)
   - Wire enforceNoHedging in the post-run path
   - Wire upstream-readiness audit (if non-PM agent)
   - Wire approval-confirm + escalation paths

  STATE
   - Add the new agent's phase(s) to runtime/routing/types.ts and runtime/routing/agent-registry.ts
   - Make resolveAgent() route the right phase to the new agent

  TESTS
   - Add Scenario N<NN> in tests/integration/workflows.test.ts exercising main path
   - Extend log-coverage invariant if the agent adds new state mutations

  MANUAL SCENARIOS
   - Add MT-N entries to MANUAL_TESTS.md (orientation, draft save, approval, hedge gate, escalation)
   - Bump CODE_MARKER in runtime/boot-fingerprint.ts if new bracketed log lines added

  DOCS (Definition of Done)
   - AGENTS.md (persona, capabilities, inputs/outputs)
   - SYSTEM_ARCHITECTURE.md (place in spec chain, audit owned)
   - BACKLOG.md (move from active to completed)
   - .env.example (any new WorkspaceConfig field)

  ENFORCEMENT-AUDIT TABLE
   - Fill out the table in docs/CONTRIBUTING_AGENTS.md and store in the PR description.
`)
}

if (require.main === module) {
  main()
}

export { pathFor, buildAgentTemplate, buildTestTemplate }
